### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by brainstorm** [seanh/snapshotter#31]
rsnapshot has a `.conf` file where one can define paths to backup, snapshotter seems to lack this.

While writing an ansible recipe I realized that I had to write paths in ansible's group variables, which does not allow me to decouple deployment from backup specs :/

@guillermo-carrasco

**Comment by brainstorm** [comment]
For reference should this get implemented: https://wiki.archlinux.org/index.php/Rsnapshot

**Comment by seanh** [comment]
@brainstorm Is this something that couldn't be achieved by writing scripts that call snapshotter?

I have lots of `~/bin/backup_*` scripts in my home, that look like:

    #!/usr/bin/env
    snapshotter <options> <args>

**Comment by brainstorm** [comment]
Good point, that should be enough for our purposes I guess :+1:

**Comment by seanh** [comment]
Hope you find it useful!
